CC/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    #App Core
    path('', include('core.urls', namespace='pages_tvm')),

    #App Admin Django
    path('admin/', admin.site.urls),
   
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.convertCase, name='convertCase'),
    path('home', views.home, name='home'),
    path('tests', views.tests, name='tests'),
    path('privacy-policy', views.privacy, name='privacy'),
    path('terms', views.terms, name='terms'),

    
    
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return HttpResponse("<h1>I'm Home!</h1>")

def convertCase(request):
    return render(request, 'pages/convertCase.html')

def tests(request):
    return render(request, 'pages/tests.html')

def privacy(request):
    return render(request, 'pages/privacy-policy.html')

    
def terms(request):
    return render(request, 'pages/terms.html')

core/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="">
       
    <title> {% block title %} {% endblock %}  </title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/navbar-static/">
    <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <!-- CSS tvm local -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/navbar-top.css' %}">
    <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Acme&display=swap" rel="stylesheet">


    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %} " type="image/x-icon" sizes="48x48" type="image/png"
    <meta name="theme-color" content="#7952b3">

    <!-- Custom styles for this template -->
    <link href="/assets/css/navbar-top.css" rel="stylesheet">
  </head>
  <body>
    
    <!--Menu -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Convert Case ++</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"         aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0")
     
      
        <li class="nav-item"> <a class="nav-link" id="menu-tvm" href="#">Small Text Generator</a></li>
        <li class="nav-item"> <a class="nav-link" id="menu-tvm" href="#">Wide text</a></li>
        <li class="nav-item"> <a class="nav-link" id="menu-tvm" href="#">Strikethrough-text</a></li>
        <li class="nav-item"> <a class="nav-link" id="menu-tvm" href="#">Reverse Text</a></li>
        <li class="nav-item"> <a class="nav-link" id="menu-tvm" href="#">Upside Down Text</a></li>
        <li class="nav-item"> <a class="nav-link" id="menu-tvm" href="#">Morse Code Translator</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span  id="more-tools">[ More Tools ]</span>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown" id="ul-menu">
            <li><a class="dropdown-item" id="menu-tvm" href="#">Underline Text</a></li>
            <li><a class="dropdown-item" id="menu-tvm" href="#">Mirror Text</a></li>
            <li><a class="dropdown-item" id="menu-tvm" href="#">Unicode Text</a></li>
            <li><a class="dropdown-item" id="menu-tvm" href="#">Bubble Text</a></li>
            <li><a class="dropdown-item" id="menu-tvm" href="#">Sentence Case</a></li>
            <li><a class="dropdown-item" id="menu-tvm" href="#">Zalgo Glitch Text</a></li>
            <li><a class="dropdown-item" id="menu-tvm" href="#">Online Notepad</a></li>
            <li><a class="dropdown-item" id="menu-tvm" href="#">Online Text Tools</a></li>
          </ul>
    </div>
  </div>
</nav>
  
    {% block content %}
   
    {% endblock %}
  

<br><br>
<!-- footerInfo-->
<div class="container-fluid text-center">
<div class="alert alert-warning role="alert">Infos:</h4>
   <p id="links-tvm">Copyright ©2021-<span id="year"></span><strong> Convert Case ++</strong> | developed by
        
          <!-- Button trigger modal -->
<button type="button" class="btn btn-outline-dark btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Thiago Viana
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Infos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <ul class="thiago-list">
              <p>Thiago Viana</p>
              <p>E-mail: tvm.dev2015@gmail.com</p>
<p>Website: <a href="https://professorthiago.com.br" target="_blank">ProfessorThiago.com.br</a></p>
        </ul>
       
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
    </div>
  </div>
</div>
        <a href="{% url 'pages_tvm:convertCase' %}" class="btn btn-outline-dark btn-sm">Home</a> 
        <a href="{% url 'pages_tvm:privacy' %}" class="btn btn-outline-dark btn-sm">Privacy Policy</a> 
        <a href=" {% url 'pages_tvm:terms' %} " class="btn btn-outline-dark btn-sm">Terms of Use </a>
        <a href="#" class="btn btn-outline-dark btn-sm">Cookies Settings</a>
        <a href="#" class="btn btn-outline-dark btn-sm">SiteMap</a>
        <a href="#" class="btn btn-outline-dark btn-sm">About</a> 
            




    <!--End Detais-->
  </div>
</div>
</footer>


<!-- scripts online -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script> 
<!-- scripts tvm local -->
<script src="{% static 'js/scripts.js' %}"></script>
      
  </body>
</html>

core/templates/pages/convertCase.html
{% extends 'base.html' %}


{% block title %} Convert Case ++ {% endblock %}


{% block content %}

<main class="container-fluid">
  <div class="bg-light p-3 rounded">
       <h2 class=".text-wrap fw-bold">Accidentally left the caps lock on and typed something, but can't be bothered to start again and retype it all?</h2>
    
       <p class="lead text-center">Simply: enter your text and choose the case you want to convert it to.</p>

        <!--Ads 01-->
        
        <!--End ads01-->

  
    
        <textarea class="form-control" rows="10" id="content" placeholder="Type ou past your content here" onkeyup="counterAll(this);" autofocus></textarea>
        <span class="text-muted pull-left" id="countChar"></span>
        <span class="text-muted pull-left" id="countWords"></span>
        <span class="text-muted pull-left" id="countLines"></span>
    
        <p id="copied"></p>

    
    <!--Buttons-->
    <div class="form-control text-center">
    <button onclick="Sentence()" type="button" class="btn btn-primary mb-1 btn-sm">Sentence case</button>
    <button onclick="Lower()" type="button" class="btn btn-secondary mb-1 btn-sm">lower case</button>
    <button onclick="Upper()" type="button" class="btn btn-success mb-1 btn-sm">UPPER CASE</button>
    <button onclick="capitalizedCase()" type="button" class="btn btn-danger mb-1 btn-sm">Capitalized Case</button>
    <button onclick="inverseCase()" type="button" class="btn btn-warning mb-1 btn-sm">InVeRsE CaSe</button>
    <button onclick="reverseWord()" type="button" class="btn btn-info mb-1 btn-sm">Reverse Word</button>
    <button onclick="spaceLetters()" type="button" class="btn btn-outline-primary mb-1 btn-sm">Character Spacing</button>
    <button onclick="removeSpaces()" type="button" class="btn btn-outline-secondary mb-1 btn-sm">Remove Spaces</button>
    <button onclick="commaSpace()" type="button" class="btn btn-outline-success mb-1 btn-sm">Comma Space</button>
    <button onclick="downloadText(content.value,'ConvertCase ++.txt')" type="button" class="btn btn-outline-danger mb-1 btn-sm">Download Text</button>
    <button onclick="copyToClipboard()" type="button" class="btn btn-outline-dark mb-1 btn-sm">Copy to Clipboard</button>
    <button onclick="Clean()" type="button" class="btn btn-dark mb-1 btn-sm">Clean</button><hr>
    <!--end buttons-->

     

    <!--Ads 02-->
    <!--End ads02-->




      </div>
    </div>
  
</main>
<br>

<!--start infos-->

<!-- Sentense Case-->
<div class="container-fluid">
<p class="h3 text-center alert alert-info">Welcome to the [Convert Case ++] Text Generator Tool</p>

<div class="alert alert-primary role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
  Sentense Case:
  
  </h4>
  <p class="text-justify mb-1">
  The sentence case converter will allow you to paste any text you’d like, and it will automatically transform it to a fully formed structured sentence.
  It works by capitalizing the very first letter in each sentence, and will then go on to transform the rest of the text into lowercase as well as converting i’s into I’s. Every letter after a full stop will get converted into an upper case letter.
  Note: it won’t, however, capitalize names or places.<br><br>
<p class="form-control text-center">This is an example of sentence case.</p>

</div>

<!-- Lower Case -->
<div class="alert alert-secondary role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
    Lower Case:
   
   </h4>
   <p class="text-justify mb-1">
  If you are wondering how to uncapitalize text, this is exactly what the lower case text converter will allow you to do - it transforms all the letters in your text into lowercase letters. Simply copy the text that you need generating into lower case and paste the text into the box above and select the ‘lower case’ tab.<br><br>
 <b class="form-control text-center">this is an example of lower case.</b>
 </p>
 </div>

<!--  UPPER CASE-->
<div class="alert alert-success role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
    UPPER CASE:
   
   </h4>
   <p class="text-justify mb-1">
  The upper case transformer will take any text that you have and will generate all the letters into upper case ones. It will essentially make all lower case letters into CAPITALS (as well as keep upper case letters as upper case letters).

  To do this, you simply have to select the text that you need changing and pasting into the box above and then select the UPPER CASE tab.<br><br>
 <b class="form-control text-center">THIS IS AN EXAMPLE OF UPPER CASE.</b>
 </p>
 </div>
<!-- Capitalized Case-->
<div class="alert alert-danger role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
    Capitalized Case:
   
   </h4>
   <p class="text-justify mb-1">
  The capitalized case converter will automatically convert the starting letter of every word into an upper case and will leave the remaining letters as lower case ones.

Simply copy the content that you will like to generate into this format, then paste into the box form above and select the Capitalized Case tab.<br><br>
 <b class="form-control text-center">This Is An Example Of Capitalized Case.</b>
 </p>
 </div>
<!-- InVeRsE CaSe-->
<div class="alert alert-warning role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
    InVeRsE CaSe:
   
   </h4>
   <p class="text-justify mb-1">
  The Inverse case inverse each typed letter to its opposite. The capital letter becomes lowercase and vice versa.

Simply copy the content that you will like to generate into this format, then paste into the box form above and select the Capitalized Case tab.<br><br>
 <b class="form-control text-center">tHIS IS AN EXAMPLE OF SENTENCE CASE.</b>
 </p>
 </div>
<!-- Reverse Word-->
<div class="alert alert-info role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
    Reverse Word:
   
   </h4>
   <p class="text-justify mb-1">
  Reverse Word reverses the typed word. It's as if the word is rotated 180 degrees. See an example below:<br><br>
 <b class="form-control text-center"> USA => ASU or Jesus => suseJ </b>
 </p>
 </div>
<!-- Character Spacing-->
<div class="alert alert-primary role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
    Character Spacing:
   
   </h4>
   <p class="text-justify mb-1">
    The Character Spacing puts a space between each letter of the typed text and does not put commas between these spaces:<br><br>
 <b class="form-control text-center"> United States => U n i t e d   S t a t e s </b>
 </p>
 </div>
<!-- Remove spaces-->

<div class="alert alert-light role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
    Remove spaces:
   
   </h4>
   <p class="text-justify mb-1">
    The remove spacing button removes any spaces that exist between words or phrases - leaving the text fully together:<br><br>
 <b class="form-control text-center"> S p a c e => Space </b>
 </p>
 </div>


<!-- Comma Space-->
<div class="alert alert-success role="alert">
 <h4 class="alert-heading"><img src="https://www.freeiconspng.com/thumbs/information-icon/info-icon--6.png" width=30px" height="30px">
   
    Comma Space:
   
   </h4>
   <p class="text-justify mb-1">
    This button places a comma between each word or phrase and even removes any space between words or phrases:<br><br>
 <b class="form-control text-center"> Australia => A,u,s,t,r,a,l,i,a </b>
 </p>
 </div>


<!-- Download Text-->
<!-- Copy to Clipboard-->
<!-- Clean-->




</div>

{% endblock %}

core/templates/pages/tests.html
{% extends 'base.html' %}


{% block title %} tests {% endblock %}


{% block content %}
  <img align="center" src="https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif" width="100px">

 



{% endblock %}